### PR TITLE
Added ability to shuffle task order.

### PR DESCRIPTION
**Pull request by Lythimus**
Removed some outdated references and fixed typos as well. I couldn't find anywhere which allowed random sorting or I would have plugged that in as an option as well. So I just removed it from the front end.

### CODE REVIEW

**Comment by teleyinex** [comment]
This is really nice. Would you mind to add a few tests as well as documentation? We cannot merge it without them. Basically test that RANDOM is called (otherwise this is going to be difficult to be tested) and also be sure that you add the docs here: http://docs.pybossa.com/en/latest/user/project_settings.html?highlight=scheduler#task-scheduler

Explain how it works, and we will merge it :D

**Comment by teleyinex** [comment]
Are you still interested in merging this PR?

**Comment by Lythimus** [comment]
@teleyinex Yeah, but there definitely needs to be some modifications, in addition to creating proper tests are called. I'm finally testing out the functionality and it seems new_task is invoked twice by the presenter. I'm not entirely sure why, possibly for the progress bar, but because I'm sorting by random, two different new tasks are being returned. For the most part workers can resolve tasks, but when the second to last task comes up, half the time two different tasks are grabbed. So I guess when checking to see what's next after the second to last task is resolved, the presenter just displays that all tasks are complete.

I've tried playing with setting the seed based on project and user ids, which would provide a consistent shuffle if all tasks were remaining, but I'm not getting the behavior I expected, so I'm going to continue digging to determine what's causing newtask to be called twice and check if there's not a way to stop the penultimate short circuiting.

**Comment by teleyinex** [comment]
We've recently added a cool feature to the /api/task endpoint. Basically, you can get any task for any project excluding tasks where the current user has participated. Then, it's completely up to you in the front end to present the tasks in the order that you want :-D

Just check this [docs](http://docs.pybossa.com/en/latest/api.html?highlight=participated#excluding-contributed-tasks-from-get-queries)

**Pull request closed without merging**
