### PR TITLE
Two factor auth

### PR DESCRIPTION
**Pull request by fiorda**
Hello! We've been using pybossa for a while and added some custom features to it. We were thinking about contributing them back if you'd like.
This pr adds the possibility of adding two factor authentication on login; if this feature is enabled, after entering their login credentials users will receive a one time password in their email to use to complete the login process.
Any comment/suggestion is welcome!

### CODE REVIEW

**Comment by therealmarv** [comment]
wow, cool. I also thought about this feature but I did not had spare time on investigating this. Have you signed up the [contributing agreement](https://github.com/Scifabric/pybossa/blob/master/CONTRIBUTING.md)?

**Comment by dtws** [comment]
we submitted an entity contributor agreement a while back; do I need to sign an individual agreement as well?

**Comment by fiorda** [comment]
we submitted an entity contributor agreement a while back; do I need to sign an individual agreement as well?

**Comment by therealmarv** [comment]
If you are acting fully on behalf of the entity then no. If you are acting privately or you are not directly connected to the entitity then yes. Btw, which entitity?

If the tests are green and we are ok with the code we will merge it.

Just one requirement at this stage: It would be cool if otp is overall optional and default turned off (opt in with settings_local.py/settings_local.py.tmpl).

Sorry for jumping through this many hoops.

**Comment by fiorda** [comment]
The agreement was signed on may 5th and it should be covering contributions from https://github.com/bloomberg/pybossa.
Test right now is red because the default template is missing some files - I added a pull request for that. And yes, the otp is optional, turned off by default; to turn it on, one needs to set `ENABLE_TWO_FACTOR_AUTH = True` in `settings_local.py`.

**Comment by therealmarv** [comment]
I've merged your theme changes to a new branch `add-otp` for now on the theme https://github.com/Scifabric/pybossa-default-theme/pull/144

Please checkout this branch and let pybossa reference to that your commit on the submodule there.

Let's see if it will get green.

**Comment by fiorda** [comment]
Well that didn't work. I'll look into it

**Comment by fiorda** [comment]
Some tests were failing after https://github.com/Scifabric/pybossa-default-theme/pull/142

**Comment by therealmarv** [comment]
Hi @fiorda Just inform you: I will review and merge it if everything ok at the beginning of next week.

**Comment by fiorda** [comment]
Thank you @therealmarv, if there's something you want me to modify, please let me know!

**Comment by fiorda** [comment]
Added paragraph in documentation

**Comment by therealmarv** [comment]
thanks @fiorda ! Well done. Will be merged in https://github.com/Scifabric/pybossa/pull/1591

**Comment by fiorda** [comment]
Thank you @therealmarv and @teleyinex :-)

**Pull request closed without merging**
