### PR TITLE
Update VM to Ubuntu 16.04 and Postgres 9.5

### PR DESCRIPTION
**Pull request by alexandermendes**
I was testing out some JSON queries and thinking of updating some columns to use JSONB (for #1720) and realised that the VirtualBox/Vagrant VM is still running with Postgres 9.3, as this is the highest default version for Ubuntu 14.04. That makes testing a bit difficult without messing around with the setup manually etc. So this PR upgrades the setup to use Ubuntu 16.04, and therefore Postgres 9.5, which are your officially supported versions, of course :smiley:

There are some issues with the official ubuntu/xenial64 vagrant image, in that the vagrant user isn't included by default ([see bug report](https://bugs.launchpad.net/cloud-images/+bug/1569237)). I toyed with upgrading to 17.10, or creating the vagrant user manually, but instead the easiest thing to do was to go for the bento/ubuntu-16.04 image instead, which works without having to mess around with things too much.

### CODE REVIEW

**Comment by alexandermendes** [comment]
Also, this seems to work without issues on Windows too, which is something I've struggled with a bit before!

**Comment by therealmarv** [comment]
Hi @alexandermendes 

Two things:
- I appreciate to test out PYBOSSA with Ubuntu <16.04 but I cannot merge that because we (Scifabric) will not support non LTS Ubuntu versions (it's only that non LTS versions are getting out too fast and we don't want to help people to move every 6 or couple of months to a new Ubuntu version). So the next target for us is the next LTS which is 18.04 LTS. So I cannot merge that ;)
- For Redis and Sentinel we moved internally entirely away from Ubuntu repos because we compile the newest versions ourselfs (currently 4.x) and use supervisord for keeping redis up. This is maybe also the way to go for Vagrant instances (which are only meant for a test drive). But I think your systemd approach is good enough for Vagrant and looks good.

**Comment by alexandermendes** [comment]
Hi @therealmarv 

Ok, so that all makes sense, I can see that you don't want to be constantly moving to new Ubuntu versions. I mostly just wanted a Vagrant box with Postgres >= 9.5 installed. This could be done manually with the current PYBOSSA 14.04 Vagrant setup but that's obviously not ideal. 

What do you want to do then? Sounds like you want to wait until 18.04 before updating the Vagrant setup, or do you think there's something we can do in the meantime?

**Comment by therealmarv** [comment]
I think if you change it to the bento Ubuntu 16.04 box we can use that till 18.04 reaches at least beta status.

**Comment by alexandermendes** [comment]
Cool, so that was the most recent commit :wink: I know things got a bit messy!

**Comment by therealmarv** [comment]
very cool, missed the most recent commit somehow. I will test first and merge it then.

**Comment by alexandermendes** [comment]
Great, thanks

**Comment by alexandermendes** [comment]
I think there are still a couple of issues with this:

1. Redis sentinel starts up fine but it doesn't restart
2. The root user doesn't have 'vagrant' set as the password

I see you're talking about creating Docker containers too, so maybe we can just use that instead. Might still try to solve the above.

**Comment by therealmarv** [comment]
Docker is the future. We will have soon a alpha/beta version here with some Docker compose or Docker Stack (not ready yet). Doing a last test of your code right now and gonna merge it then.

**Pull request merged**
