### PR TITLE
Add featured to public attributes

### PR DESCRIPTION
**Pull request by alexandermendes**

### CODE REVIEW

**Comment by alexandermendes** [comment]
Similar story with user.admin, leaving it out of public attributes breaks the managing admin users page. Don't suppose this will be a privacy issue.

**Comment by teleyinex** [comment]
Hi!

We don't understand why is failing for you, as we can manage users in the admin dashboard. Can you elaborate? We're not saying that you are wrong, just want to understand the issue :-)

**Comment by alexandermendes** [comment]
Ok, maybe I jumped to conclusions with admin users, it was definitely the reason for featured projects though. I'll checked today and see where I've gone wrong with that one!

**Comment by alexandermendes** [comment]
Yep, my mistake, I suppose it was a long day (excuses, excuses)! Have updated it to just deal with the featured projects bit.

**Comment by teleyinex** [comment]
Haha :D No worries man! This is fine, so merging it :-)

**Pull request merged**
