### PR TITLE
import local csv

### PR DESCRIPTION
**Pull request by dchhabda**

### CODE REVIEW

**Comment by teleyinex** [comment]
Hi,

I like a lot this importer. Also, I was thinking if it will make more sense to upload the file to TempFile instead to the container of the user. This will simplify things I guess, as those files will be deleted by the system and we avoid having issues with disk space. @dchhabda what do you think? Happy to work on it.

**Comment by dchhabda** [comment]
Agree, TempFile would simplify things. However, with bulk tasks import performed by background job [here](https://github.com/Scifabric/pybossa/blob/f5fa7466a493332777a81febb93a15cc94b0f39a/pybossa/view/projects.py#L662) under distributed environment having workers running on multiple instances, there are chances that file uploaded under TempFile may not be visible to worker executing import job on different instance than the instance where file upload took place.

**Comment by teleyinex** [comment]
Yep, I forgot about that. Then, it makes total sense about this. Also, in another PR we can add support for Excel files (we recently added support to our pybossa command line tool) so we can import both things and make this complete. 

I'll add a few more tests, as the Form is not being tested so we can have this ready for next week.

**Comment by dchhabda** [comment]
I add few test cases around the Form

**Comment by teleyinex** [comment]
Hi @dchhabda I just added two new tests to bump the coverage: https://github.com/Scifabric/pybossa/pull/1660 If you like them, we'll merge them on Monday. What do you think?

**Comment by dchhabda** [comment]
This is great @teleyinex, thanks.

**Comment by teleyinex** [comment]
We'll do the merging in coming hours!

**Comment by teleyinex** [comment]
This PR will be merged [here](https://github.com/Scifabric/pybossa/pull/1660) as it has better coverage.

**Comment by dtws** [comment]
Thanks

**Pull request closed without merging**
