### PR TITLE
Vm fixes

### PR DESCRIPTION
**Pull request by alexandermendes**
Here are a couple of fixes for the Vagrant setup on Windows machines.

1. Fix for redis-sentinel exe not existing. I can't find the info for this now so either some Windows issue (don't remember seeing it on a Mac) or something with recent versions of Redis. Running redis-server --sentinel should do the same thing anyway.

2. The Vagrantfile has been updated to avoid `ERROR: problem running ansible_hosts --list ([Errno 8] Exec format error)`, which happens on Windows as the hosts file gets marked as executable when `/vagrant/provisioning/hosts` is used.

### CODE REVIEW

**Comment by alexandermendes** [comment]
Oops, actually that isn't the issue with Redis, it's that the config file isn't found, with a fresh PYBOSSA clone I get this.

```
==> default: TASK: [start Sentinel and enable it at boot] **********************************
==> default: failed: [127.0.0.1] => {"failed": true}
==> default: msg: failed determining service state, possible typo of service name?
==> default:
==> default: FATAL: all hosts have already failed -- aborting
==> default:
```

SSHing in and running redis-sentinel manually gives:

```
[26818] 30 Nov 13:29:45.679 # Warning: no config file specified, using the default config. In order to specify a config
file use redis-sentinel /path/to/sentinel.conf
```

**Comment by alexandermendes** [comment]
Reverting the Redis bit until I figure that out, might be something to do with my setup. But I think the other Vagrantfile bit definitely helps!

**Comment by therealmarv** [comment]
wow thanks for the Windows fixes. Actually nobody of us is able to test it because it is untestable without a native Windows running on real hardware. I will test the current modifications once and merge it once ok.

**Comment by alexandermendes** [comment]
Currently working on a Windows machine behind a web proxy, which makes things extra frustrating, but it might at least throw out a few things like this that can be fixed!

**Comment by alexandermendes** [comment]
Resubmitted in https://github.com/Scifabric/pybossa/pull/1757 as this one had a few messy commits

**Pull request closed without merging**
