### PR TITLE
Generate on demand project report

### PR DESCRIPTION
**Pull request by dchhabda**
Hello,
We've developed a feature that can generate project report in csv form. This report has two parts containing information on project and users contributed to that project. Hope you find it useful.

The sample report would look like,

Project Statistics |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | --
Id | Name | Short Name | Total Tasks | First Task Submission | Last Task Submission | Average Time Spend Per Task | Task Redundancy
2 | Company Description | companydescription | 150 | 2017-11-11T11:50:28.479330 | 2017-11-13T19:39:21.365752 | 0.11 | 1
  |   |   |   |   |   |   |  
User   Statistics |   |   |   |   |   |  
Id | Name | Fullname | Total Tasks Completed | Percent Tasks Completed | First Task Submission | Last Task Submission | Average Time Per Task
1 | user_3 | user_3 | 6 | 4 | 2017-11-11T11:50:28.479330 | 2017-11-13T19:28:22.439752 | 0.12
4 | user_1 | user_1 | 2 | 1 | 2017-11-13T19:37:58.062088 | 2017-11-13T19:38:01.038465 | 0.09
5 | user_2 | user_2 | 2 | 1 | 2017-11-13T19:39:18.718189 | 2017-11-13T19:39:21.365752 | 0.09

### CODE REVIEW

**Comment by teleyinex** [comment]
This looks really good. Apologies for not getting back to you earlier.

**Comment by teleyinex** [comment]
Can you add this information to the [docs](https://github.com/Scifabric/docs.pybossa.com)?

**Comment by dtws** [comment]
Glad to know that you liked this feature; thanks for merging. I'll update docs soon.

**Comment by dchhabda** [comment]
Glad to know that you liked this feature. I'll update docs soon.

**Comment by dchhabda** [comment]
updated doc [here](https://github.com/Scifabric/docs.pybossa.com/pull/18)

**Pull request merged**
