### PR TITLE
Project owner can create co-owners

### PR DESCRIPTION
**Pull request by fiorda**
Hello,

We developed this feature to give project owners the ability to add 'co-owners' to their project; a co-owner is a user that has the same access level to the project as the owner.
Please let me know what you think about it.

### CODE REVIEW

**Comment by teleyinex** [comment]
Hi! This is really nice! Quick question: what about using arrays in the project table? I mean, what if instead of adding a new table, we add a new column in the projects tables with a name *owners* that's a PostgreSQL [array](https://www.postgresql.org/docs/9.1/static/arrays.html)? 

Then, we can do queries like this:

```sql
SELECT value_variable = ANY ('{1,2,3}'::int[])
```
More info [here](https://stackoverflow.com/a/11231965/1960596). Also, this is supported by [SQLAlchemy](https://stackoverflow.com/questions/10344468/sqlalchemy-how-to-filter-on-pgarray-column-types/10344851#10344851).

We've done this for tasks user's favorites, and it works really well. Check it out [here](https://github.com/Scifabric/pybossa/blob/master/pybossa/model/task.py#L54). 

I think this arrays feature of PostgreSQL is underused and this could be a straightforward solution for PYBOSSA for handling teams of owners. What do you think?

**Comment by fiorda** [comment]
Thank you for your comment! I think using arrays is a good idea; I can't see any downsides to that, and it keeps the db schema and models much cleaner. I will change the code to use arrays instead of an additional table.

**Comment by teleyinex** [comment]
@fiorda great! I like the arrays because it simplifies a lot handling a lot of tables, and arrays work really well :-) Looking forward to the changes!

**Comment by teleyinex** [comment]
Nice work!

**Comment by teleyinex** [comment]
@fiorda we're now using this [repository](https://github.com/Scifabric/docs.pybossa.com) for adding the docs. Would you mind to add it there? This is a really cool feature! Don't hesitate to contact us about the new docs style. We can now write docs in Markdown making it faster.

**Comment by teleyinex** [comment]
Also, we've created a Gitter chat room, so we can talk about PYBOSSA development. [Join us!](https://gitter.im/Scifabric/pybossa)

**Comment by alexandermendes** [comment]
This is something I've been thinking would be useful for a long time, thanks @fiorda 😄

**Comment by fiorda** [comment]
Thank you @teleyinex and @alexandermendes , I'm very glad you like this feature! I will update the documentation and join the chat 😄.

**Pull request merged**
