### PR TITLE
Api search

### PR DESCRIPTION
**Pull request by teleyinex**
This new PR will allow using the @> Postgresql operator within the info fields. Basically, you will be able to get all the domain objects that follow a path like this:

```
http://localhost:5001/api/taskrun?info={"answer":[{"relevant":false}]}
```
NOTE: you might need to escape your URL if you are using it directly from JS, otherwise chrome does the work for you.

### CODE REVIEW

**Comment by teleyinex** [comment]
@alexandermendes this is the first approach for using @> JSONB operator. It's sooo cool and powerful. And the best part is that it's backwards compatible ;-)

**Comment by teleyinex** [comment]
This new query format now allow us to do really complex queries like this:

```
http://localhost:5001/api/task?info={%22entities%22:%20{%20%22media%22:%20[{%22source_user_id%22:1}]}}
```
Basically, you can get to any nested data by writing its path within JSON. This one is like this entities->media -> [{source_user_id: value}]

**Comment by KrzysztofMadejski** [comment]
Is it limited only if you have an admin API key? Won't such queries hit hard on the database?

**Comment by teleyinex** [comment]
Hi,

This works for anyone :-)

It won't hit hard at all. Actually, JSONB stores the data efficiently. Also, you can build reverse indexes. I've been testing with Crowdcrafting DB and without an index, it takes around 2s to return something. With an index, it returns it in 0.02 ms. And this is why PostgreSQL is so cool!!

Also, you can create specific indexes, as your data may be different due to the JSON free format.

**Comment by therealmarv** [comment]
:cake: :cake:

**Pull request merged**
