### PR TITLE
Fix spa oauth

### PR DESCRIPTION
**Pull request by alexandermendes**
Close https://github.com/Scifabric/pybossa/issues/1650, close https://github.com/Scifabric/pybossa/issues/1647

### CODE REVIEW

**Comment by teleyinex** [comment]
Loving this PR. I'll investigate why it's failing and help you.

**Comment by alexandermendes** [comment]
Thanks, it's passing now though!

**Comment by teleyinex** [comment]
@alexandermendes thanks for your help on this!

**Comment by teleyinex** [comment]
:cake:

**Comment by alexandermendes** [comment]
My pleasure 😄

**Pull request merged**
