### PR TITLE
Add stats param to project endpoints

### PR DESCRIPTION
**Pull request by alexandermendes**
Seems to do the job but let me know if you have any suggestions for improving this!

### CODE REVIEW

**Comment by alexandermendes** [comment]
See https://github.com/Scifabric/pybossa/issues/1849

**Comment by teleyinex** [comment]
Can you add a test to /api/task?stats=true so we can see that it reports an error back? Just to be sure ;-)

**Comment by teleyinex** [comment]
Merging it as soon as it passes the tests ;-)

**Comment by teleyinex** [comment]
Final note: can you add this info into docs.pybossa.com?

**Comment by alexandermendes** [comment]
Thanks :)

**Pull request merged**
