### PR TITLE
Add project id/name routes

### PR DESCRIPTION
**Pull request by jayflo**
Add `projectid` routes.  Add project "short name" routes for API.

### CODE REVIEW

**Comment by teleyinex** [comment]
Hi,

This is also really cool. Actually, we've been thinking about this for a long time now, but we think that the current API provides more or less the same functionality that you are trying to build. For example, for retrieving  the project based on the short_name you can always use a query like this:

```
https://crowdcrafting.org/api/project?short_name=darkskies&all=1
```

That will return the project by its short_name (which is unique) and the &all flag will allow you to see the project, even if you are not the owner. Then, based on the owner, you will get all the private data of the project or just the public one.

If you are trying to use the name for the *newtask* endpoint, then, fixing that endpoint to allow as well getting tasks will be easier than this PR. 

Thus, would the previous query work for you? If the answer is not: why not?

Thanks for the amazing work!

**Comment by jayflo** [comment]
For the api, that query will work.  I believe the only difference being the URL and that it returns the project as a list, rather than an object (since the short_name is unique).

**Comment by teleyinex** [comment]
So would you be able to use that instead of building all the new implementation? From the frontend it will be really easy to handle the array, so you can always get that without problems.

**Comment by jayflo** [comment]
Yes, that makes sense.  Thanks.

**Pull request closed without merging**
