### PR TITLE
Issue 1676

### LINKED ISSUE #1676: redirect_content_type doesn't work when uploading images
As stated in the docs, when uploading images via the API (at `/account/<name>/update` and `/project/<short_name>/update`) we can't sent the content type to JSON. I finally managed to get image uploads working via the API but at each of those endpoints, as we're using [handle_content_type](https://github.com/Scifabric/pybossa/blob/167577773a7308df03e1b611509d86f0ed52c5bb/pybossa/util.py#L63), we don't get the correct response back. Ideally we would still get a JSON response back, with any flash messages etc. Not sure about the solution yet but I guess we need some fix there!

### PR DESCRIPTION
**Pull request by alexandermendes**
Fixes #1676

### CODE REVIEW

**Comment by alexandermendes** [comment]
A note added to the docs here https://github.com/Scifabric/docs.pybossa.com/pull/17

**Comment by alexandermendes** [comment]
Ok so redirect_content_type obviously isn't going to work for OAuth, we'll need some other solution here...

**Comment by alexandermendes** [comment]
I think that's Travis failing for some other reason. 

Anyway, how about this, encoding the message and passing it back as a hash. Then on the spa client we can get the flash messages with something like this

```js
if (process.browser && window.location.hash) {
      const hash = window.location.hash
      const decodedHash = decodeURIComponent(hash).replace(/^#/, '')
      const jsonStr = atob(decodedHash)
      const json = JSON.parse(jsonStr)
      this.flash(json)
    }
```

**Comment by alexandermendes** [comment]
Maybe putting it as a hash param was confusing so changing it to `flash=hashed_message`. I guess alternative is perhaps a session variable but this seems pretty straightforward.

**Comment by alexandermendes** [comment]
Just realised I let old submodules creep in, so fixed that

**Comment by teleyinex** [comment]
Would love to talk about this. Are you around in Gitter?

**Comment by alexandermendes** [comment]
Sure, be there within the hour

**Comment by alexandermendes** [comment]
Hopefully good to go on this one now?

**Pull request merged**
