### PR TITLE
feature password policy for user accounts

### PR DESCRIPTION
**Pull request by deepjchgit**

### CODE REVIEW

**Comment by deepjchgit** [comment]
Hello,
We would like to contribute to Pybossa community, a feature that applies strong password policy when creating new accounts. This can make the platform secure. 

Feature can be applied with configuring ENABLE_STRONG_PASSWORD=True under settings_local.py
Supported password policy is to set password length between 8 to 15 characters, at least one uppercase, one numeric and one special character from !@$%^&*#

**Comment by teleyinex** [comment]
Hi,

This is really great. One thing, we usually create the global variables in here: https://github.com/Scifabric/pybossa/blob/master/pybossa/extensions.py

The whole idea is that we have one local place to store None/Null or empty variables that will be initialized in pybossa.core. Thus, if you can move the declaration of enable_global_password to that file, then it would follow the same style as with the other variables. We then create a new function named: def setup_strong_password or something similar, and there we set up the global variable and enable the configuration (if the config file has it).

For example, for the ratelimits variable (that you can modify via the settings file as well) we do the following:

1.- At [pybossa.extensions.py](https://github.com/Scifabric/pybossa/blob/master/pybossa/extensions.py#L116) we define it.

2.- At [pybossa.core.py](https://github.com/Scifabric/pybossa/blob/master/pybossa/core.py#L622) we configure it.

So, if you can modify the code to follow this pattern, it will keep consistency in the code base. Please, ask us any questions :-)

**Comment by fiorda** [comment]
Hello @teleyinex, thank you very much for your feedback. Since @deepjchgit is now on vacation, I made the changes you suggested; please let me know if you have any other comment.

**Comment by teleyinex** [comment]
If the tests pass, tomorrow we will merge it :-)

**Pull request merged**
