### PR TITLE
Locked scheduler

### PR DESCRIPTION
**Pull request by fiorda**

### CODE REVIEW

**Comment by fiorda** [comment]
Created this pr so we can discuss our implementation of a locked scheduler.
As mentioned in https://github.com/Scifabric/pybossa/issues/1863, we use redis to store the lock in the form of a redis hash for each task; the key for each hash depends on the task id, and the hash itself maps the users that requested the task to the time the lock will expire.

There are a few consequences and design decision I would like to point out:

- the locks are only acquired through the `/newtask` endpoint; this to prevent the user from locking too many tasks by using the direct url
- there is a check on the offset parameter, again to prevent a single user to lock too many tasks at the same time
- since the locks are stored in redis, we had to implement a [user count](https://github.com/Scifabric/pybossa/pull/1878/files#diff-818837ad2f20f7b8415825710dde7de8R191) to make sure the database query returns enough tasks to have at least one that's still available

**Comment by teleyinex** [comment]
This looks really nice! Let us take a look and get back to you.

**Comment by osecki** [comment]
@teleyinex Have you had a chance to have a look? We are really excited about contributing this feature to Scifabric, especially since it was something being requested via #1863, and hope you find it a good contribution. Thanks!

**Comment by teleyinex** [comment]
Hi,

Apologies, we've not been able to check it yet, but we will. No worries! I'll keep you posted!

**Comment by teleyinex** [comment]
Closing it as we're sending a new PR based on this code but rebasing it from master.

**Pull request closed without merging**
