### PR TITLE
Migrate info tables to JSONB format.

### PR DESCRIPTION
**Pull request by teleyinex**
NOTE: this will only delete the materialed view users_rank. If you have
your own leaderboards based on info keys of the user, then you will have
to delete them manually or it will fail. Then, your background jobs will
recreate them.

### CODE REVIEW

**Comment by teleyinex** [comment]
@alexandermendes just review this :-) It's time to move towards JSONB.

**Comment by alexandermendes** [comment]
Fantastic :smile: 

I'm still hoping to build a search interface into our frontend which would have to use some complicated nested JSONB queries, so this is a really helpful step!

**Comment by teleyinex** [comment]
I'll submit a second PR with such jsonb examples :D I'm starting with nested keys and fulltextsearch! This is going to be really fun and powerful!

**Comment by alexandermendes** [comment]
Great, really looking forward to this!

**Pull request merged**
