### PR TITLE
Two factor auth from bloomberg

### PR DESCRIPTION
**Pull request by therealmarv**

### CODE REVIEW

**Comment by teleyinex** [comment]
We're only missing here the docs, right? Can we add a section after [Validation of new user accounts](https://github.com/Scifabric/pybossa/blob/master/doc/customizing.rst#L785). Something like One Time Password for user creations, so people can know that this new feature is available.

**Comment by teleyinex** [comment]
@fiorda the rest looks really cool :-)

**Comment by fiorda** [comment]
Thank you! I am going to add a section to the documentation.

**Comment by teleyinex** [comment]
@fiorda I fixed a conflict after merging #1588 Now, the only missing part is the docs. As soon as you have it, we can merge it.

**Pull request merged**
