### PR TITLE
Issue 1712

### LINKED ISSUE #1712: Add fields to domain objects retrieved via standard API routes
As we get ready to launch our first full SPA, and depart further from logic laid down before PyBossa enabled this, it would be great to add in a few fields to the domain objects returned via the API. For example, one of the things I need to do now is retrieve all featured projects that are also in a particular category, and be able to show the overall progress etc. of those projects. So, I'm currently thinking of adding things like `n_tasks`, `category_id` and the `featured` flag for projects returned via `/api/project`. I know you see this already but having maximum flexibility here would really help in future!

### PR DESCRIPTION
**Pull request by alexandermendes**
Close #1712

### CODE REVIEW

**Comment by alexandermendes** [comment]
Tests coming up!

**Comment by alexandermendes** [comment]
Ok, I think that's done

**Comment by teleyinex** [comment]
:cake:

**Comment by teleyinex** [comment]
@alexandermendes can you add to the new [docs](https://github.com/Scifabric/docs.pybossa.com/blob/master/docs/api.md) this information? Once you do it, I'll merge it.

**Comment by alexandermendes** [comment]
Sure, just a small update but see https://github.com/Scifabric/docs.pybossa.com/pull/12

**Comment by alexandermendes** [comment]
Thanks :smile:

**Pull request merged**
